<a href="https://colab.research.google.com/github/paulrobustelli/python_demos/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import linalg
from numpy.linalg import *
import scipy
from scipy.linalg import schur, eigvals, svd

In [ ]:
a=np.zeros((2,2))

In [ ]:
a

array([[0., 0.],
       [0., 0.]])

In [ ]:
a[0]

array([0., 0.])

In [ ]:
a[0]=[1,0]
a[1]=[0,1]
a

array([[1., 0.],
       [0., 1.]])

In [ ]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[2,4],[6,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [ ]:
print(a)
det(a)

[[1 2]
 [3 4]]


-2.0000000000000004

In [ ]:
print(b)
det(b)

[[2 4]
 [6 8]]


-8.000000000000002

In [ ]:
print(a)
print(b)
np.dot(a,b)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


array([[14, 20],
       [30, 44]])

In [ ]:
c=np.linalg.inv(a)
print(c)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
np.dot(a,c)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
M=np.array([[-6,3],[4,5]])
M

array([[-6,  3],
       [ 4,  5]])

In [ ]:
eigvec1=np.array([1,4])
M1=np.dot(M,eigvec1)
print("M1",M1)
eigvec1*6
#Therefore 6 is the eigenvalue and [1,4] is an eigenvector 

M1 [ 6 24]


array([ 6, 24])

In [ ]:
#Show how to find eigenvectors and eigenvalues manually
eigvals,eigvecs=np.linalg.eig(M)
print(eigvals)
D=np.array([[6,0],[0,-7]])
P=np.array([[1,-3],[4,1]])
print(eigvecs)
print(D)
print(P)
Pinv=inv(P)
print(Pinv)
np.dot(np.dot(P,D),Pinv)
#print(eigvecs[0])
#print(eigvecs[1])
#L,X=schur(M)
#print("L:",L)
#print("X:",X)

[-7.  6.]
[[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]
[[ 6  0]
 [ 0 -7]]
[[ 1 -3]
 [ 4  1]]
[[ 0.07692308  0.23076923]
 [-0.30769231  0.07692308]]


array([[-6.,  3.],
       [ 4.,  5.]])

In [ ]:
print(M)
eigvals,eigvecs=np.linalg.eig(M)
print(eigvals)
print(eigvals[0])
print(eigvals[1])

[[-6  3]
 [ 4  5]]
[-7.  6.]
-7.0
6.0


In [ ]:
a=np.zeros((4,4))
a[0]=[0,1,0,0]
a[1]=[1,0,1,0]
a[2]=[0,1,0,1]
a[3]=[0,0,1,0]

In [ ]:
a

array([[0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.]])

In [ ]:
T,Z = schur(a)
np.around(T,decimals=3)

array([[-1.618, -0.   ,  0.   , -0.   ],
       [ 0.   , -0.618,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  1.618, -0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.618]])

In [ ]:
np.around(Z,decimals=3)

array([[ 0.372,  0.602, -0.372, -0.602],
       [-0.602, -0.372, -0.602, -0.372],
       [ 0.602, -0.372, -0.602,  0.372],
       [-0.372,  0.602, -0.372,  0.602]])

In [ ]:
a

array([[0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 0., 1., 0.]])

In [ ]:
#cyclobutadiene
a=np.zeros((4,4))
a[0]=[0,1,0,1]
a[1]=[1,0,1,0]
a[2]=[0,1,0,1]
a[3]=[1,0,1,0]
T, Z = schur(a)
np.around(T,decimals=3)

array([[-2., -0., -0., -0.],
       [ 0.,  0., -0.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:
np.around(Z,decimals=3)

array([[ 0.5  , -0.707,  0.5  ,  0.   ],
       [-0.5  , -0.   ,  0.5  , -0.707],
       [ 0.5  ,  0.707,  0.5  ,  0.   ],
       [-0.5  , -0.   ,  0.5  ,  0.707]])

In [ ]:
#Benzene:
#cyclobutadiene
a=np.zeros((6,6))
a[0]=[0,1,0,0,0,1]
a[1]=[1,0,1,0,0,0]
a[2]=[0,1,0,1,0,0]
a[3]=[0,0,1,0,1,0]
a[4]=[0,0,0,1,0,1]
a[5]=[1,0,0,0,1,0]

T, Z = schur(a)
np.around(T,decimals=3)

array([[-2.,  0.,  0., -0., -0.,  0.],
       [ 0.,  2., -0., -0., -0.,  0.],
       [ 0.,  0.,  1., -0.,  0., -0.],
       [ 0.,  0.,  0., -1.,  0., -0.],
       [ 0.,  0.,  0.,  0., -1., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [ ]:
np.around(Z,decimals=3)

array([[ 0.408, -0.408, -0.577,  0.577, -0.006,  0.   ],
       [-0.408, -0.408, -0.289, -0.294, -0.497, -0.5  ],
       [ 0.408, -0.408,  0.289, -0.284,  0.503, -0.5  ],
       [-0.408, -0.408,  0.577,  0.577, -0.006, -0.   ],
       [ 0.408, -0.408,  0.289, -0.294, -0.497,  0.5  ],
       [-0.408, -0.408, -0.289, -0.284,  0.503,  0.5  ]])

In [ ]:
a=np.zeros((3,3))
a[0]=[-7.2,-1.0,-0.8]
a[1]=[-1,-10.4,0]
a[2]=[-0.8,0,-8.4]

In [ ]:
a

array([[ -7.2,  -1. ,  -0.8],
       [ -1. , -10.4,   0. ],
       [ -0.8,   0. ,  -8.4]])

In [ ]:
T, Z = schur(a)
np.around(T,decimals=3)

array([[ -6.585,  -0.   ,   0.   ],
       [  0.   , -10.709,   0.   ],
       [  0.   ,   0.   ,  -8.705]])

In [ ]:
a

array([[ -7.2,  -1. ,  -0.8],
       [ -1. , -10.4,   0. ],
       [ -0.8,   0. ,  -8.4]])

array([[-2., -0., -0., -0.],
       [ 0.,  0., -0.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:
a=np.zeros((3,3))
a[0]=[0,1,1]
a[1]=[1,0,1]
a[2]=[1,1,0]


In [ ]:
a

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

In [ ]:
T,Z = schur(a)
np.around(T,decimals=3)

array([[-1.,  0., -0.],
       [ 0.,  2., -0.],
       [ 0.,  0., -1.]])

In [ ]:
np.around(Z,decimals=3)

array([[-0.816,  0.577,  0.   ],
       [ 0.408,  0.577, -0.707],
       [ 0.408,  0.577,  0.707]])